// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlaizzpasjfmjauaqbtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsYWl6enBhc2pmbWphdWFxYnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDE1MDIsImV4cCI6MjA2MzE3NzUwMn0.6K7g1QLjzx5IQ-TklAtuEV2cF9MnSqmYXLnXZoV5Uxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);